[NbConvertApp] Converting notebook Part3_Transformer.ipynb to notebook
[NbConvertApp] ERROR | Timeout waiting for execute reply (3600s).
Traceback (most recent call last):
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbclient/client.py", line 778, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 182, in ensure_async
    result = await obj
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/jupyter_client/channels.py", line 315, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guylevy/miniconda3/envs/cs236781-hw/bin/jupyter-nbconvert", line 10, in <module>
    sys.exit(main())
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/jupyter_core/application.py", line 277, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/traitlets/config/application.py", line 1043, in launch_instance
    app.start()
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 414, in start
    self.convert_notebooks()
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 589, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 555, in convert_single_notebook
    output, resources = self.export_single_notebook(
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 481, in export_single_notebook
    output, resources = self.exporter.from_filename(
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 201, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 220, in from_file
    return self.from_notebook_node(
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/exporters/notebook.py", line 36, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 154, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 352, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/preprocessors/base.py", line 48, in __call__
    return self.preprocess(nb, resources)
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 100, in preprocess
    self.preprocess_cell(cell, resources, index)
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 121, in preprocess_cell
    cell = self.execute_cell(cell, index, store_history=True)
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbclient/client.py", line 1001, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbclient/client.py", line 802, in _async_poll_for_reply
    error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
  File "/home/guylevy/miniconda3/envs/cs236781-hw/lib/python3.8/site-packages/nbclient/client.py", line 852, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 3600 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['# fit your model', 'import pickle', "if not os.path.exists('trained_transfomer_encoder.pt'):", '    from hw3.training import TransformerEncoderTrainer', '    trainer = TransformerEncoderTrainer(model, criterion, optimizer)']
...
['    ', '', "saved_state = torch.load('trained_transfomer_encoder.pt')", "best_acc = saved_state['best_acc']", "model.load_state_dict(saved_state['model_state'])"]
-------------------

Got errors while executing notebook Part3_Transformer.ipynb. Make sure you've implemented everything and that all tests pass.
>> Running 1 notebooks...
>> Running nbconvert on notebook Part3_Transformer.ipynb [execute|inplace]
